### ISSUE TITLE
The code issue

### ISSUE THREAD

**Issue by Rooders** [XL2248/CPCC#2]
Hello, thank you for your released code. This is great work. 
There are some questions about the implementation of recognition and prior networks what was mentioned in your paper.
1. The two networks have the same structure in your paper, i.e , MLP and MLP + Softplus, right? But in your released code, It seems that the structure of recognition networks is Linear layer + Linear layer, and the one of prior network is an MLP.
2. It seems that the Sigma and Mu in Gussian distribution have been gotten from the same network in your released code. i.e, you passed the network once, then split the output of the network into two matrixes as Sigma and Mu, right? But in your paper, the Mu and Sigma have been gotten by MLP and Softplus + MLP, respectively.

So I wonder about which one is more effective and can reach the performance that has been reported in your paper.

**Comment by XL2248** [comment]
Hi,
Both two methods are common in related work to obtain Sigma and Mu. And no significant differences are observed in our preliminary experiments. Just using the released code will be okay.

**Comment by Rooders** [comment]
> Hi, Both two methods are common in related work to obtain Sigma and Mu. And no significant differences are observed in our preliminary experiments. Just using the released code will be okay.

Thanks for your reply, and Is it also OK for the difference between recognition and prior networks? I feel a little fused because it is different from the description in your paper.

**Comment by XL2248** [comment]
Thanks for pointing out this difference. I think it is ok (of course, you can try different implementations about it) and I will upload another one described same with the paper.
